server:
  port: 8762

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/raullopezz/lab6-microservices-config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/